[package]
name = "veritas-app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "veritas"
path = "src/main.rs"

[dependencies]
eframe = { version = "0.24.1", features = ["persistence", "default"] }
egui = "0.24.1"
egui_plot = "0.24.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1.0", features = ["full"] }
csv = "1.3"
anyhow = "1.0"
directories = "5.0"
plotters = "0.3.3"
winapi = { version = "0.3", features = ["winuser"] }